### ISSUE TITLE
EPIPE error when evaluating.

### ISSUE THREAD

**Issue by HelloWorld017** [espadrine/localeval#6]
When I evaluate my code which has eval timeout using localeval, an EPIPE error occurs randomly.

stacktrace:

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:856:11)
    at ChildProcess.target._send (internal/child_process.js:611:20)
    at ChildProcess.target.send (internal/child_process.js:507:19)
    at evaluator (D:\heworkspace\overrun-online\node_modules\localeval\localeval.js:50:13)
    at module.exports (D:\heworkspace\overrun-online\src\evaluate.js:5:2)
    at D:\heworkspace\overrun-online\plugins\overrun\overrun-game.js:109:5
    at null._onTimeout (D:\heworkspace\overrun-online\node_modules\localeval\localeval.js:37:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by espadrine** [comment]
What is the associated code?

**Comment by HelloWorld017** [comment]
The issue was too old to remember 😅, but AFAIK that might be my local machine's problem related to the antivirus, as I have found out spawning process on another applications was also randomly killed, at that time.

Sorry for completely forgetting to update & close this issue.
